version: "4.24.2"
services:
  appfinal: 
    build: .
    ports:
      - "3000:3000" 
    links:
      - monguito 
  monguito: 
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=steven
      - MONGO_INITDB_ROOT_PASSWORD=783836